# Nom de notre workflow
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Événements sur lesquels il doit être déclenché
  push:        # <- Déclenché lorsque l'on pousse du code...
    branches: ["main"] # <- ... mais seulement sur la branche "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Notre job
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
     # Tâches à effectuer, comme expliquées ci-dessus
    steps:
       # 1. On récupère le contenu du dépôt
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
        #on a besoin d'installer les library geos sur la machine avant
      - name: install geos
        run: |        
          sudo apt install libgeos-dev   
      - name: Build 
        run: |
          Rscript 'dev/render_site.R'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2